@Library ('shared_lib') _
properties([
    parameters([
        string(name: 'parameter_name', defaultValue: '', description: "Parameter Description")
        string(name: 'GIT_URL', defaultValue: '', description: 'Git url')
        string(name: 'BRANCH', defaultValue: '', description: 'Branch')
    ])
])
pipeline{
    agent any //{label 'agent_name'}
    environment{
        SONAR_HOME = tool 'Sonar'
        BRANCH = "${params.BRANCH_REF ?: ''}".replace('refs/heads/', '')
    }

    stages{
        stage('Build only if branch == master'){
            when {
                        expression{ env.BRANCH != 'master'}
                    }
            steps{
                script{
                    currentBuild.result = 'SUCCESS'
                    error(Branch is not master : env.BRANCH)
                    
                }
            }
        }
        stage('Validate the credentials'){
            steps{
                script{
                    if (param.parameter_name == ''){
                        error('parameter_name cannot the empty')
                    }
                }
            }
        }
        stage('Clean workspace'){
            steps{
                script{
                    clean_ws()
                }
            }
        }
        stage('Git: code checkout'){
            when {
                expression { params.GIT_URL != ''}
            }steps{
                script{
                    code_checkout()
                }
            }
        }
        stage('Trivy scan'){
            steps{
                script{
                    trivy_scan(target: ".",
                        type: "fs",
                        severity: "MEDIUM,HIGH,CRITICAL",
                        failOnVuln: false
                    )
                }
            }
        }
        stage('Sonar Scan'){
            steps{
                script{
                    sonarScan(projectKey: "my-app",sources: ".")
                }
            }
        }
        stage('OWASP Scan'){
            steps{
                script{
                    oswap_scan()
                }
            }
        }
        stage('DockerHub Image Push'){
            steps{
                script{
                    dockerHub_login()
                }
            }
        }
        stage('Send the report via email'){
            steps{
                script{
                    email_report()
                }
            }
        }

    }
}
