pipeline {
    agent {
        label 'agent_name'
    }

    environment {
        SONAR_HOME = tool 'sonar'
    }

    parameters {
        string(name: 'gitUrl', defaultValue: '', description: 'Git url')
        string(name: 'branch', defaultValue: '', description: 'Git branch')
    }

    stages {

        stage('Validate the git url') {
            steps {
                script {
                    if (params.gitUrl == '') {
                        error('Failed: Git Url is empty')
                    }
                }
            }
        }

        stage('Validate the git branch') {
            steps {
                script {
                    if (params.branch != 'master' && params.branch != 'main') {
                        error('Failed: Non-master/non-main branch')
                    }
                }
            }
        }

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Git clone') {
            steps {
                git branch: "${params.branch}",
                    url: "${params.gitUrl}"
            }
        }

        stage('Install the required packages') {
            steps {
                sh 'pnpm i'
            }
        }
        stage('SonarQube Scan'){
            steps{
                withSonarQubeEnv('sonar'){
                    sh '''
                        ${SONAR_HOME}/bin/sonar-scanner \
                        -Dsonar.projeectKey=public-service \
                        -Dsonar.sources=.
                    '''
                }
            }
        }

        stage('Quality Gate'){
            steps{
                timeout(time: 5, unit: 'MINUTES'){
                    script{
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK'){
                            error('Quality Gate Failed: ${qg.status}')
                        }
                    }
                }
            }
        }
        stage('Build the app') {
            steps {
                sh '''
                    cd public-service
                    pnpm run public-service:build
                '''
            }
        }
    }
}