pipeline{
    agent any \\ {label 'agent_name'}
    environment{
        SONAR_HOME = tool 'sonar'
    }
    parameters{
        string(name: gitUrl, defaultValue: '', description: 'Git url')
        string(name: branch, defaultValue: '', description: 'Git branch')
    }
    stages{
        stage('Validate the git url'){
            when{
                expression{params.gitUrl == ''}
            }
            steps{
                script{
                    currentBuild.result == "SUCCESS"
                    error('Failed: Git url is empty: params.gitUrl')
                }
            }
        }

        stage('Validate the git branch'){
            steps{
                script{
                    if(params.branch != 'master' || params.branch != 'main' )
                    error('Faild: Non-master/non-main branch')
                }
            }
        }
    }
}